version: '3'

services:
  mysql-sx:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: easy-shop
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    mem_limit: 512m
