// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"database/sql"

	"github.com/google/uuid"
)

type Person struct {
	ID      uuid.UUID
	Name    sql.NullString
	Age     sql.NullInt32
	Cpf     sql.NullString
	Address sql.NullString
	UserID  uuid.NullUUID
}

type Resource struct {
	ID          uuid.UUID
	Name        sql.NullString
	Description sql.NullString
}

type Role struct {
	ID          uuid.UUID
	Name        sql.NullString
	Description sql.NullString
}

type RolesResource struct {
	ID         uuid.UUID
	RoleID     uuid.NullUUID
	ResourceID uuid.NullUUID
}

type User struct {
	ID       uuid.UUID
	Email    sql.NullString
	Password sql.NullString
}

type UsersResource struct {
	ID             uuid.UUID
	UserID         uuid.NullUUID
	RoleResourceID uuid.NullUUID
}
